name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - rspi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configuring tailscale on the runner
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          
      - name: SSH into Raspberry Pi and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          password: ${{ secrets.PI_PASSWORD }}
          script: |
            cd /home/sasi/Sentilytics-rspi
            git pull origin rspi
          



