name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - rspi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Raspberry Pi and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 4.tcp.ngrok.io
          username: ${{ secrets.PI_USERNAME }}
          password: ${{ secrets.PI_PASSWORD }}
          port: 12267
          script: |
            cd /home/sasi/Sentilytics-rspi
            git pull



